const ACTIONS = {
  UPDATE_USER: "UPDATE_USER",
  UPDATE_BOARDS: "UPDATE_BOARDS",
  UPDATE_COLUMNS: "UPDATE_COLUMNS",
  UPDATE_BOARD_ITEMS: "UPDATE_BOARD_ITEMS",
  UPDATE_TASKS: "UPDATE_TASKS",
};

export default ACTIONS;
